import "oaidl.idl";
import "unknwn.idl";

[object, uuid(C3C38ECD-6377-4560-9D48-D9E493728F77)]
interface IPingable : IUnknown {
	HRESULT Initialize();
	HRESULT Ping([in] SHORT pingCode, [out] SHORT * statusCode);
}

[uuid(6D2530EA-D5D8-46EC-A994-3AD1036BDC9B), version(1.0)]
library PingLib {

	[uuid(5819432D-806B-42C1-97DE-DE5A015A8497)]
	coclass CoPingEngine {
		[default] interface IPingable;
	};
}

cpp_quote("DEFINE_GUID(PingLib, 0x5819432d, 0x806b, 0x42c1, 0x97, 0xde, 0xde, 0x5a, 0x01, 0x5a, 0x84, 0x97);")
cpp_quote("DEFINE_GUID(IID_IPingable, 0xc3c38ecd, 0x6377, 0x4560, 0x9d, 0x48, 0xd9, 0xe4, 0x93, 0x72, 0x8f, 0x77);")
cpp_quote("DEFINE_GUID(CLSID_CoPingEngine, 0x5819432d, 0x806b, 0x42c1, 0x97, 0xde, 0xde, 0x5a, 0x01, 0x5a, 0x84, 0x97);")