import "oaidl.idl";

[object, uuid(C3C38ECD-6377-4560-9D48-D9E493728F77), oleautomation]
interface IPingable : IUnknown {
	HRESULT Initialize();
	HRESULT Ping([in] SHORT pingCode, [out, retval] SHORT * statusCode);
}

[uuid(6D2530EA-D5D8-46EC-A994-3AD1036BDC9B), version(1.0)]
library PingLib {
	interface IPingable;

	[uuid(5819432D-806B-42C1-97DE-DE5A015A8497)]
	coclass CoPingEngine {
		[default] interface IPingable;
	};
}